### ISSUE TITLE
Install error: MLX

### ISSUE THREAD

**Issue by Relysis** [0ssamaak0/CLIPPyX#33]
PyTorch install works fine, and the clippyx install seems to work until hitting the below error.  Tried with both Python 3.13 and 3.12, but no difference

INFO: pip is looking at multiple versions of mlx-embeddings to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement mlx>=0.16.3 (from mlx-embeddings) (from versions: none)
ERROR: No matching distribution found for mlx>=0.16.3

**Comment by 0ssamaak0** [comment]
hi, I'm finalizing the MLX version soon. I will fix these issues and provide a pytorch free version for macs! Just give me some time

**Comment by Prettyprettygood** [comment]
Running into this issue on windows - which seems strange.

**Comment by Relysis** [comment]
My issue is on windows as well.  Thanks 0ssamaak0 for the work

**Comment by oceanondawave** [comment]
You’re hitting this because mlx only exists for macOS + Apple Silicon. On Windows/Linux (or Intel Mac) `pip` will always fail with _No matching distribution_.

👉 Fix = skip MLX and use Hugging Face models instead:

1. Fresh venv (Windows example)
```
python -m venv C:\v\clx
C:\v\clx\Scripts\activate
python -m pip install -U pip
```

2. Install without MLX deps
```
pip install -e . --no-deps
findstr /V /I "mlx" requirements.txt > requirements.win.txt
pip install -r requirements.win.txt
pip install -U transformers sentencepiece pillow pyyaml
```

Then in `config.yaml` set:

```
clip:
  provider: HF_transformers
  HF_transformers_clip: openai/clip-vit-base-patch32

text_embed:
  provider: HF_transformers
  HF_transformers_embeddings: sentence-transformers/all-MiniLM-L6-v2
```

Run with:

`CLIPPyX`

✅ This avoids MLX and works fully offline.
