### ISSUE TITLE
Include / Execlude some Folders

### ISSUE THREAD

**Issue by 0ssamaak0** [0ssamaak0/CLIPPyX#4]
In windows version, `Everything` by default gets all image
from `config.yaml` user can use `include_folders` / `exclude_folders` to manage this.

## Implementation
There're 2 suggested approaches
1. get all images from `everything_images.py` and later add/remove according to given dirs (slower)
2. Everything itself has this functionality, but we have to explore [the SDK](https://www.voidtools.com/support/everything/sdk/) to see how to this

**Comment by marshal-dteach** [comment]
@0ssamaak0 I would like to work on this, can you assign this issue to me?

**Comment by 0ssamaak0** [comment]
yeah ofc, I assigned you.

I also updating `config.yaml` to contain the followign settings
``` yaml
# config.yaml
# Folders settings: Select folders to include / exclude for indexing
include_folders:
    - all # default (Comment this if you want to specify folders)
    # - path/to/folder1
    # - path/to/folder2

exclude_folders:
    # - path/to/folder1
    # - path/to/folder2
```
and imported them in `everything_images`

- please check `Everything SDK` to check how to index by including and excluding, don't filter in python file unless there's no way with `Everything SDK`
- handle the `all` case as the default case
   
Thank you very much for help!
